name: terminal
services:
#  reverse-proxy:
#    container_name: terminal.reverseproxy
#    image: nginx:latest
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./Config/nginx:/etc/nginx/:ro
#      - ./Config/cert:/etc/ssl/:ro
#    depends_on: [server, client]

  client:
    container_name: terminal.client
    build: "./Client"
    ports:
      - 60005:5173
    restart: always
    depends_on: ["server"]

  server:
    container_name: terminal.server
    build: "./Server/src"
    ports:
      - 60004:5006
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - Jwt__Issuer=${Jwt__Issuer}
      - Jwt__Audience=${Jwt__Audience}
      - Jwt__SecretKey=${Jwt__SecretKey}
      - Postgres__ConnectionString=${Postgres__ConnectionString}
      - Administrator__Email=${Administrator__Email}
      - Administrator__Password=${Administrator__Password}
    restart: always
    depends_on: ["database"]

  database:
    container_name: terminal.postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/terminalData:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    restart: always
    pull_policy: missing
